// export const BASE_URL = 'http://192.168.0.117:8000/'
export const BASE_URL = 'http://192.168.0.117:8080'


export const CHECKTOKEN_URL = BASE_URL + '/api/check_token'
export const USER_URL = BASE_URL + '/api/user'
export const ADDINGPART_URL = BASE_URL + '/api/add_equipment_child'
export const UPGRADEPART_URL = BASE_URL + '/api/save_changes'
export const DELETEPART_URL = BASE_URL + '/api/delete_equipment?id='
export const PARENTPART_URL = BASE_URL + '/api/equipment_data?parent_equipment_id='
export const ALLPART_URL = BASE_URL + '/api/equipment_child?parent_equipment_id='
export const NEWPARENTPART_URL = BASE_URL + '/api/add_equipment'
export const UPGRADEIMAGE_URL = BASE_URL + '/api/change_image'
export const UPGRADENAME_URL = BASE_URL + '/api/change_name'
export const ALLMODELS_URL = BASE_URL + '/api/equipment'
export const DELETEMODEL_URL = BASE_URL + '/api/delete_equipment?id='

export const ADDINGLOCATION_URL = BASE_URL + '/api/add_location'
export const ALLLOCATION_URL = BASE_URL + '/api/location?id='
export const PARENTLOCATION_URL = BASE_URL + '/api/parent_location?id='
export const SPLITLOCATION_URL = BASE_URL + '/api/split_location'
export const CHANGELOCATION_URL = BASE_URL + '/api/change_location'
export const DELETELOCATION_URL = BASE_URL + '/api/delete_location?id='
